### ISSUE TITLE
Support replacements

### ISSUE THREAD

**Issue by sandro-h** [sandro-h/snippet#5]
Allow to specify certain special strings which will be replaced automatically when typing the snippet.

For example:
* The current date - allow to specify the format using the standard Golang time formatting pattern
* The current user

To consider: same as arguments, might have to list the replacements explicitly to avoid accidentally replacing something meant to be verbatim.
One idea is to extend the `args` option to allow a list of maps, where the type of arg is specified. E.g.:
```yaml
args:
  - host:
       type: input
  - date:
       type: now
       format: ...
```
If any arg is of type `input`, show the arg window, otherwise only do automatic replacements.
The short-form args list should still work and treat all the elements as type `input`.
